name: deploy production app

on: 
  push:
    branches: [ production ]

env:
  DOCKER_DIRECTORY: edupals-docker

jobs:
  test:
    uses: ./.github/workflows/ci_test.yml
    secrets: 
      env_file: |
        API_URL=https://example.com
    with:
      environment: test
    
  build:
    uses: ./.github/workflows/build_web.yml
    needs: [test]
    secrets: 
      env_file: |
        API_URL=${{ secrets.PRODUCTION_API_URL }}
    with:
      environment: production

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]
    environment: production
    steps:
      - name: Pulling docker images
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ vars.PRODUCTION_HOSTS }}
          privateKey: ${{ secrets.PRODUCTION_SSH_KEY }}
          command: |
            cd ~/${{ env.DOCKER_DIRECTORY }}
            docker-compose pull web
      - name: Recycle all the containers
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ vars.PRODUCTION_HOSTS }}
          privateKey: ${{ secrets.PRODUCTION_SSH_KEY }}
          command: |
            cd ~/${{ env.DOCKER_DIRECTORY }}
            docker-compose up -d --force-recreate web
  