name: deploy review app

on: 
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  APP_NAME: ${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}
  IMAGE_REPO: ghcr.io/${{ github.repository }}
  EXPOSED_PORT: '80'
  COMMENT_MESSAGE: 'Successfully deployed to [${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}.${{vars.DOKKU_HOST}}](https://${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}.${{vars.DOKKU_HOST}})! :rocket:'

jobs:
  test: 
    uses: ./.github/workflows/ci_test.yml
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    secrets: 
      env_file: |
        API_URL=${{ secrets.STAGING_API_URL }}
    with:
      environment: staging

  build:
    needs: [test]
    uses: ./.github/workflows/build_web.yml
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    secrets: 
      env_file: |
        API_URL=${{ secrets.STAGING_API_URL }}
        GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
        SENTRY_DSN=${{ secrets.SENTRY_DSN }}
    with:
      environment: staging
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    # do not run if it is closed
    if: github.event_name == 'pull_request' && github.event.action != 'closed' 
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - name: Rebuild Review Apps
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: root@${{ vars.DOKKU_HOST }}
          privateKey: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          command: |
            if dokku apps:exists ${{ env.APP_NAME }};
            then 
              dokku git:from-image ${{ env.APP_NAME }} ${{ env.IMAGE_REPO }}@${{ needs.build.outputs.image_digest }};
            else 
              dokku apps:create ${{ env.APP_NAME }};
              dokku domains:set ${{ env.APP_NAME }} ${{ env.APP_NAME }}.${{ vars.DOKKU_HOST }};
              dokku letsencrypt:enable ${{ env.APP_NAME }};
              dokku proxy:ports-set ${{ env.APP_NAME }} http:80:${{ env.EXPOSED_PORT }} https:443:${{ env.EXPOSED_PORT }};
              dokku git:from-image ${{ env.APP_NAME }} ${{ env.IMAGE_REPO }}@${{ needs.build.outputs.image_digest }};
            fi
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: execution
          message: |
            ${{ env.COMMENT_MESSAGE }}

  destroy:
    runs-on: ubuntu-latest
    # only run when a pull request is closed
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    environment: staging
    steps:
      - name: Rebuild Review Apps
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: root@${{ vars.DOKKU_HOST }}
          privateKey: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          command: |
            if dokku apps:exists ${{ env.APP_NAME }};
            then
              dokku --force apps:destroy ${{ env.APP_NAME }};
            fi
      - name: Rebuild Review Apps 2
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: root@${{ vars.DOKKU_HOST }}
          privateKey: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          command: |
            if dokku apps:exists ${{ env.APP_NAME }};
            then
              dokku --force apps:destroy ${{ env.APP_NAME }};
            fi

  